# 1. Build stage
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files first (better caching)
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy rest of the code
COPY . .

# Expose Next.js port
EXPOSE 3000

# Start app
CMD ["npm", "run", "dev"]