version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app         # sync local files with container
      - /app/node_modules # avoid overwriting node_modules
    environment:
      NODE_ENV: development
